name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_run:
    workflows: ["develop branch"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [5.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See https://github.com/actions/setup-java
          java-version: '17'
          cache: 'gradle'
      - run:  ./gradlew clean build integrationTest jacocoTestReport --no-daemon
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2 # See https://github.com/cicirello/jacoco-badge-generator
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: .github/badges
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          generate-branches-badge: false
          branches-badge-filename: branches.svg
          generate-coverage-endpoint: false
          coverage-endpoint-filename: jacoco.json
          generate-branches-endpoint: false
          branches-endpoint-filename: branches.json
          generate-summary: false
          summary-filename: coverage-summary.json
          coverage-label: coverage
          branches-label: branches
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          intervals: 100 90 80 70 60 0
          on-missing-report: fail
          fail-if-coverage-less-than: 0
          fail-if-branches-less-than: 0
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false
      - run:
          git config --global user.name "github-actions[bot]" &&
          git config --global user.email "51759+github-actions[bot]@users.noreply.github.com" &&
          sed -i -E 's/^(!\[test status\].*)(\?cache-buster=.+)/\1?cache-buster='$RANDOM'\)/' README.md &&
          git add .github/badges/jacoco.svg README.md &&
          git commit -m "Update jacoco.svg" .github/badges/jacoco.svg README.md &&
          git push &&
          git fetch --unshallow &&
          git checkout -B develop origin/develop &&
          git merge master --no-edit &&
          git push || true
