name: feature branches
on:
  push:
    branches: [ 'feature/**', 'develop' ]
  pull_request:
    branches: [ 'feature/**', 'develop' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [5.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See https://github.com/actions/setup-java
          java-version: '17'
          cache: 'gradle'
      - run:  ./gradlew clean build integrationTest --no-daemon
